### ISSUE TITLE
Considering for adoption

### ISSUE THREAD

**Issue by pjhampton** [jenkinsci/junit-attachments-plugin#20]
Hey @jglick 👋 

I'm interesting in adopting this plugin for maintainership as I use it on a hobby project and in a legacy work project. Just a couple of q's before I bring it to the maintainer list:

1. Does maintainership mean I can choose the direction of the plugin given that it maintains backward compatibility?

2. Is there an ETA target when fixing bugs?

3. Why are you putting this up for adoption?

Thanks
p

**Comment by pjhampton** [comment]
Timing this out. It's been a while.

**Comment by oleg-nenashev** [comment]
I will sync-up with Jesse next week and ask him

**Comment by pjhampton** [comment]
Seems like this isn't going anywhere. If you guys could do with any additional dev help, please feel free to reach out.

**Comment by TobiX** [comment]
Please see https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin for the official adoption process. The Jenkins project mostly uses Jira and mailing lists, so issues reported here will most likely fall through the cracks (especially for busy people like Jesse Glick)

**Comment by pjhampton** [comment]
@tobix thanks for your comment. The process was followed, I tried to get their attention this way, then gave up. As you said, people are busy and there is not a lot of traction in this plugin.

**Comment by oleg-nenashev** [comment]
Yes, https://groups.google.com/forum/#!searchin/jenkinsci-dev/junit-attachments-plugin%7Csort:date/jenkinsci-dev/YJTPj904ueg/bAxlY_nhDQAJ definitely fell between the cracks. I see some kind of consensus in the thread, but nobody really followed up on the permission transfer. It is somewhat my bad, because I was usually processing transfer requests at that time. We have around 30 active people who can do it (including @jglick), but uh oh. My apologies for it.

@pjhampton if you are still interested to take ownership, I can transfer it

**Comment by pjhampton** [comment]
Sounds good @oleg-nenashev

**Comment by oleg-nenashev** [comment]
So, should I transfer it?

**Comment by pjhampton** [comment]
You want to transfer it to my username? Would it not make more sense to keep it in the Jenkins org and give me commit access to the repo? That way I can shepherd it with the help of the Jenkins community.

**Comment by jglick** [comment]
> You want to transfer it to my username?

No, I think @oleg-nenashev just meant to grant you write & deploy access.

**Comment by pjhampton** [comment]
In that case, yes, please :)

**Comment by oleg-nenashev** [comment]
Done. This is the case when later than never.
Thanks a lot for your patience @pjhampton  🙇
